============================= test session starts ==============================
platform linux -- Python 3.10.11, pytest-8.3.3, pluggy-1.5.0 -- /home/user/testing/.venv/bin/python3
cachedir: .pytest_cache
Running tests in /tmp/tst.

Date: 2024-09-23T14:51:44

Platform: Linux-6.6.43-desktop-1.mga9-x86_64-with-glibc2.36

Executable: /home/user/testing/.venv/bin/python

Full Python Version: 
3.10.11 (main, Mar 26 2024, 15:00:27) [GCC 12.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: not available
Scipy: not available
Matplotlib: not available
h5py: not available
Pandas: not available


rootdir: /tmp/tst
configfile: pyproject.toml
plugins: cov-4.1.0, astropy-header-0.2.2, xdist-3.6.1
created: 2/2 workers
2 workers [9 items]

scheduling tests via LoadScheduling

compuservecvt_test.py::TestCompuserveCvt::test_message_1 
adddate_test.py::TestAdddateCvt::test_message_1 
[gw1] [ 11%] PASSED compuservecvt_test.py::TestCompuserveCvt::test_message_1 
compuservecvt_test.py::TestCompuserveCvt::test_message_2 
[gw1] [ 22%] PASSED compuservecvt_test.py::TestCompuserveCvt::test_message_2 
maillogcvt_test.py::TestMaillogCvt::test_message_1 
[gw1] [ 33%] SKIPPED maillogcvt_test.py::TestMaillogCvt::test_message_1 
maillogcvt_test.py::TestMaillogCvt::test_message_2 
[gw1] [ 44%] XPASS maillogcvt_test.py::TestMaillogCvt::test_message_2 
mantes_test.py::TestMantesCvt::test_message_1 
[gw0] [ 55%] PASSED adddate_test.py::TestAdddateCvt::test_message_1 
adddate_test.py::TestAdddateCvt::test_message_2 
[gw1] [ 66%] PASSED mantes_test.py::TestMantesCvt::test_message_1 
uupccvt_test.py::TestUupcCvt::test_message_1 
[gw0] [ 77%] PASSED adddate_test.py::TestAdddateCvt::test_message_2 
uupccvt_test.py::TestUupcCvt::test_message_2 
[gw0] [ 88%] PASSED uupccvt_test.py::TestUupcCvt::test_message_2 
[gw1] [100%] FAILED uupccvt_test.py::TestUupcCvt::test_message_1 

=================================== FAILURES ===================================
__________________________ TestUupcCvt.test_message_1 __________________________
[gw1] linux -- Python 3.10.11 /home/user/testing/.venv/bin/python3

self = <uupccvt_test.TestUupcCvt testMethod=test_message_1>

    def test_message_1(self):
>       self.run_inout_test('testdata/uupc.input.1', 'testdata/uupc.expected.1')

uupccvt_test.py:44: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
uupccvt_test.py:41: in run_inout_test
    self.assertEqual(expecteddata, actualdata)
E   AssertionError: 'From[911 chars]ding: 3 TEXT\n\n[The Response]\n\n>From the #1 source\nxyzzy\n' != 'From[911 chars]ding: 3 TEXT\n\n[The Response]\n\n>From the #1 source\n\n'
E   Diff is 998 characters long. Set self.maxDiff to None to see it.
----------------------------- Captured stderr call -----------------------------
Warning: Line needed to be escaped: From the #1 source
Messages copied:  1
Dates converted:  0
From lines added: 0
=========================== short test summary info ============================
FAILED uupccvt_test.py::TestUupcCvt::test_message_1 - AssertionError: 'From[9...
============== 1 failed, 6 passed, 1 skipped, 1 xpassed in 0.72s ===============
